name: Pelias On-Demand Builder

on:
  workflow_dispatch:

jobs:
  pelias:
    runs-on: ubuntu-latest
    steps:
    - name: Register SSH Key with Hetzner
      id: sshkey
      run: |
        KEY_NAME="pelias-builder"
        PUB_KEY="${{ secrets.SSH_PUBLIC_KEY }}"

        # Check if the key already exists
        EXISTING_ID=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
          https://api.hetzner.cloud/v1/ssh_keys \
          | jq -r --arg name "$KEY_NAME" '.ssh_keys[] | select(.name == $name) | .id')

        if [ -z "$EXISTING_ID" ]; then
          echo "Registering new SSH key with Hetzner..."
          RESPONSE=$(curl -s -X POST https://api.hetzner.cloud/v1/ssh_keys \
            -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"name": "'"$KEY_NAME"'", "public_key": "'"$PUB_KEY"'"}')
          echo "$RESPONSE"
        else
          echo "SSH key already exists with ID: $EXISTING_ID"
        fi

    - name: Create Hetzner Server
      id: create
      run: |
        SERVER_NAME=pelias-$(date +%s)

        RESPONSE=$(curl -s -X POST https://api.hetzner.cloud/v1/servers \
          -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "'"$SERVER_NAME"'",
            "server_type": "ccx13",
            "image": "docker-ce",
            "ssh_keys": ["pelias-builder"],
            "location": "ash"
          }')

        echo "$RESPONSE"
        echo "server_id=$(echo $RESPONSE | jq -r .server.id)" >> $GITHUB_OUTPUT
        echo "ipv4=$(echo $RESPONSE | jq -r .server.public_net.ipv4.ip)" >> $GITHUB_OUTPUT

    - name: Wait for SSH availability
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

        for i in {1..20}; do
          ssh -o StrictHostKeyChecking=no -i key.pem root@${{ steps.create.outputs.ipv4 }} "echo ready" && break
          echo "sleeping..."
          sleep 10
        done

    - name: Start Pelias Build on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ steps.create.outputs.ipv4 }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "running v1.0.0"
          adduser --disabled-password --gecos "" pelias
          usermod -aG docker pelias
          echo "cloning..."          
          git clone https://github.com/jcardus/pelias-docker /home/pelias/pelias-docker
          chown -R pelias:pelias /home/pelias/pelias-docker
          ln -s /home/pelias/pelias-docker/pelias /usr/local/bin/pelias
          nohup su - pelias -c 'cd pelias-docker && ./run.sh' > pelias.log 2>&1 &
          echo "waiting for pelias to start..."
          
    - name: Output server IP
      run: echo "Pelias build started at ${{ steps.create.outputs.ipv4 }}"
