name: Pelias On-Demand Builder

on:
  workflow_dispatch:

jobs:
  pelias:
    runs-on: ubuntu-latest
    steps:
    - name: Create Hetzner Server
      id: create
      run: |
        SERVER_NAME=pelias-$(date +%s)

        RESPONSE=$(curl -s -X POST https://api.hetzner.cloud/v1/servers \
          -H "Authorization: Bearer ${{ secrets.HETZNER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "'"$SERVER_NAME"'",
            "server_type": "ccx13",
            "image": "docker-ce",
            "ssh_keys": ["${{ secrets.SSH_PUBLIC_KEY }}"],
            "location": "nbg1"
          }')

        echo "$RESPONSE"
        echo "server_id=$(echo $RESPONSE | jq -r .server.id)" >> $GITHUB_OUTPUT
        echo "ipv4=$(echo $RESPONSE | jq -r .server.public_net.ipv4.ip)" >> $GITHUB_OUTPUT

    - name: Wait for SSH availability
      run: |
        for i in {1..20}; do
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ steps.create.outputs.ipv4 }} "echo ready" && break
          sleep 10
        done

    - name: Start Pelias Build on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ steps.create.outputs.ipv4 }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          git clone https://github.com/pelias/docker ~/pelias
          cd ~/pelias
          ./scripts/bootstrap.sh
          nohup bash -c './scripts/build.sh && ./scripts/prepare_all.sh && ./scripts/import_all.sh && docker-compose up -d' > pelias.log 2>&1 &

    - name: Output server IP
      run: echo "Pelias build started at ${{ steps.create.outputs.ipv4 }}"
